spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:templates/
    suffix: .html
    view-names: register, master-password, login, login-error, vault
  cache:
    type: none
  web:
    resources:
      chain:
        cache: false
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/safepass.p12
    key-store-password: ${CERT_PASSWORD}
    key-password: ${CERT_PASSWORD}
    key-alias: safepass
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    org:
      springframework:
        security: TRACE
#  h2:
#    console:
#      enabled: true
#      path: /h2
